### ISSUE TITLE
How use ?

### ISSUE THREAD

**Issue by tolgatasci** [hfreire/get-me-a-date#316]
Hello,

docker run -d -p "5941:3000" hfreire/get-me-a-date 

Browser 

http://192.168.99.100:5941/

No setting Facebook USER TOKEN 

WHERE THERE WRİTE ?

**Comment by Sillanmaki** [comment]
Can someone answer if known?

**Comment by pierreclr** [comment]
https://github.com/hfreire/get-me-a-date/pull/600
