### ISSUE TITLE
Update readme with require environment variables

### ISSUE THREAD

**Issue by hfreire** [hfreire/get-me-a-date#34]

**Comment by robot-head** [comment]
I'll take this one.  I'm currently reading through get-me-a-date source looking for which environment variables I can configure.  FACEBOOK_USER_EMAIL and FACEBOOK_USER_PASSWORD do not seem to be sufficient to get the Facebook channel showing up in the sidebar:

![image](https://user-images.githubusercontent.com/877644/30041595-1d0e1e1e-91a0-11e7-8c2d-002563e636e0.png)

**Comment by hfreire** [comment]
Hi @robot-head :) I think the available channels are not being properly bootstrapped #319 

I'll take a look at that issue later today :)

**Comment by hfreire** [comment]
The issue you've described should be fixed in v1.2.110.
