### ISSUE TITLE
Need contribution guidelines

### ISSUE THREAD

**Issue by pierreclr** [hfreire/get-me-a-date#601]
Hi there, 

I'd like to help on that project so I tried to create a small PR (close dialog after like / pass) and when I try to commit, the git pre-commit hook 
```
running bin/pre-commit.js script
Has untracked files in folder.
Please delete or ignore them.
```

So I commented the line and again, a problem about commit format 
`INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" ! was: Close dialog after like / pass`
`INVALID COMMIT MSG: "feature" is not allowed type !`

I suggest to add contribution guideline in the repo.

Anyway, I really like this project and the code style :) 
However I'm quite familiar with DialogFlow, if you want me to create a smalltalk (I'm french so I can handle this part)

**Comment by hfreire** [comment]
Hi Pierre! 

You are right! This repo is missing contribution guidelines and instructions on how to contribute. I'll add some ASAP!

The error you stumbled upon must be related with the `pre-git` dep pre-commit hook that refuses to commit if there are untracked files not included in the commit - not sure if this is a nice behaviour to have :( (?!)

Smalltalk would be a really interesting feature to have here :)

**Comment by pierreclr** [comment]
> not sure if this is a nice behaviour to have :( (?!)

My untracked file is `env.sh`. I can just add it to `.gitignore` if you want. Or just bypass the feature from pre-commit hook ? Your choice :)

**Comment by hfreire** [comment]
OK! From c505263 you should be able to have untracked files in your workspace - changed `pre-git` commit behaviour.

**Comment by hfreire** [comment]
Hi Pierre!

Let's follow up with the smalltalk behaviour on #32 :)
